name: Project map
on:
  push:
    branches:
      - "**"
permissions:
  contents: write
jobs:
  build-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y tree universal-ctags
      - name: Generate project map
        run: |
          chmod +x scripts/generate-project-map.sh
          ./scripts/generate-project-map.sh
      - name: Commit changes if any
        run: |
          if git diff --quiet docs/PROJECT_MAP.md; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/PROJECT_MAP.md
            git commit -m "chore(docs): update PROJECT_MAP.md [skip ci]"
            git push
          fi