name: Project map
on:
  push:
    branches:
      - "**"
permissions:
  contents: write
jobs:
  build-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
